import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Import logo from assets
import logo from "../assets/logo.png";

const downloadResultPDF = async (result, user) => {
  const doc = new jsPDF();

  // Convert image to Base64
  const getBase64Image = (imgUrl) => {
    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = "anonymous";

      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;

        const ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0);

        resolve(canvas.toDataURL("image/png"));
      };

      img.src = imgUrl;
    });
  };

  const logoBase64 = await getBase64Image(logo);

  // LOGO
  doc.addImage(
    logoBase64,
    "PNG",
    15,
    10,
    40,
    25
  );

  // TITLE
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");

  doc.text(
    "RESULT REPORT CARD",
    110,
    20,
    {
      align: "center",
    }
  );

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(
    "Online Examination System",
    105,
    28,
    {
      align: "center",
    }
  );

  // LINE
  doc.line(15, 40, 195, 40);

  // STUDENT DETAILS
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");

  doc.text("Student Details", 15, 52);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(
    `Student Name : ${user?.fullName || "-"}`,
    15,
    62
  );

  doc.text(
    `Email : ${user?.email || "-"}`,
    15,
    72
  );

  doc.text(
    `Generated On : ${new Date().toLocaleString()}`,
    15,
    82
  );

  // EXAM DETAILS
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");

  doc.text("Exam Details", 15, 100);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(
    `Exam Name : ${result.exam?.title || "-"}`,
    15,
    110
  );

  doc.text(
    `Subject : ${result.exam?.subject?.name || "-"}`,
    15,
    120
  );

  doc.text(
    `Submitted On : ${new Date(
      result.createdAt
    ).toLocaleString()}`,
    15,
    130
  );

  // RESULT SUMMARY TABLE
  autoTable(doc, {
    startY: 145,
    head: [["Metric", "Value"]],
    body: [
      [
        "Total Questions",
        result.totalQuestions,
      ],
      [
        "Correct Answers",
        result.correctAnswers,
      ],
      [
        "Wrong Answers",
        result.wrongAnswers,
      ],
      [
        "Obtained Marks",
        `${result.obtainedMarks}/${result.totalMarks}`,
      ],
      [
        "Percentage",
        `${result.percentage.toFixed(2)}%`,
      ],
      [
        "Result Status",
        result.resultStatus.toUpperCase(),
      ],
    ],
    theme: "grid",
  });

  const finalY =
    doc.lastAutoTable.finalY + 20;

  // FINAL RESULT
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");

  doc.text(
    "Final Result",
    15,
    finalY
  );

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(
    `Status : ${result.resultStatus.toUpperCase()}`,
    15,
    finalY + 12
  );

  doc.text(
    `Percentage : ${result.percentage.toFixed(
      2
    )}%`,
    15,
    finalY + 22
  );

  // SIGNATURE
  doc.line(
    130,
    finalY + 35,
    190,
    finalY + 35
  );

  doc.text(
    "Authorized Signatory",
    140,
    finalY + 43
  );

  // FOOTER
  doc.setFontSize(10);

  doc.text(
    "Generated by Online Examination System",
    105,
    285,
    {
      align: "center",
    }
  );

  doc.save(
    `${result.exam?.title}-Result.pdf`
  );
};

export default downloadResultPDF;